/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/age-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Age Status */
        get: operations["age_status_v1_age_verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/age-verification/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Age Session */
        post: operations["start_age_session_v1_age_verification_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/age-verification/sessions/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Age Session */
        get: operations["get_age_session_v1_age_verification_sessions__verification_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/nickname-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nickname Check */
        post: operations["nickname_check_v1_auth_nickname_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/onboarding/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile_v1_onboarding_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/age/{provider_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Age Webhook */
        post: operations["age_webhook_v1_webhooks_age__provider_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgeSessionIn */
        AgeSessionIn: {
            /**
             * Declared Birth Date
             * Format: date
             */
            declared_birth_date: string;
            /**
             * Method
             * @enum {string}
             */
            method: "selfie_estimation" | "id_document" | "spid" | "cie";
            /** Return Url */
            return_url: string;
        };
        /** AgeSessionOut */
        AgeSessionOut: {
            /** Age Band */
            age_band?: ("16_17" | "18_plus") | null;
            /** Failure Reason */
            failure_reason?: ("underage" | "inconsistent" | "not_completed") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "selfie_estimation" | "id_document" | "spid" | "cie";
            /** Redirect Url */
            redirect_url?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "passed" | "failed" | "expired";
        };
        /** AgeStatusOut */
        AgeStatusOut: {
            /** Age Band */
            age_band?: ("16_17" | "18_plus") | null;
            latest?: components["schemas"]["AgeSessionOut"] | null;
            /** Methods */
            methods: ("selfie_estimation" | "id_document" | "spid" | "cie")[];
            /** Verified */
            verified: boolean;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Feature Flags */
            feature_flags: {
                [key: string]: boolean;
            };
            legal: components["schemas"]["LegalLinks"];
            /** Min App Version */
            min_app_version: string;
            /** Styles */
            styles: components["schemas"]["StyleOut"][];
            /** Terms Version */
            terms_version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LegalLinks */
        LegalLinks: {
            /** Community Rules */
            community_rules: string;
            /** Feed Explainer */
            feed_explainer: string;
            /** Privacy */
            privacy: string;
            /** Terms */
            terms: string;
        };
        /** NicknameCheckIn */
        NicknameCheckIn: {
            /** Nickname */
            nickname: string;
        };
        /** NicknameCheckOut */
        NicknameCheckOut: {
            /** Available */
            available: boolean;
            /** Nickname */
            nickname: string;
            /** Reason */
            reason?: ("invalid" | "reserved" | "taken") | null;
        };
        /** OnboardingIn */
        OnboardingIn: {
            /**
             * Accept Community Rules
             * @constant
             */
            accept_community_rules: true;
            /**
             * Account Type
             * @default private
             * @enum {string}
             */
            account_type: "private" | "business";
            /** Nickname */
            nickname: string;
            /** Styles */
            styles: string[];
            /** Terms Version */
            terms_version: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "private" | "business";
            /**
             * Age Band
             * @enum {string}
             */
            age_band: "16_17" | "18_plus";
            /** Bio */
            bio: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Hide Prices */
            hide_prices: boolean;
            /** Hide Vote Count */
            hide_vote_count: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "suspended" | "pending_deletion";
            /** Styles */
            styles: string[];
        };
        /** ProfileUpdateIn */
        ProfileUpdateIn: {
            /** Account Type */
            account_type?: ("private" | "business") | null;
            /** Bio */
            bio?: string | null;
            /** Hide Prices */
            hide_prices?: boolean | null;
            /** Hide Vote Count */
            hide_vote_count?: boolean | null;
        };
        /** StyleOut */
        StyleOut: {
            /** Active Until */
            active_until: string | null;
            /** Min Age Band */
            min_age_band: string;
            /** Name */
            name: string;
            /** Seasonal */
            seasonal: boolean;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
            /** Tone */
            tone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    age_status_v1_age_verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeStatusOut"];
                };
            };
        };
    };
    start_age_session_v1_age_verification_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgeSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_age_session_v1_age_verification_sessions__verification_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nickname_check_v1_auth_nickname_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NicknameCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NicknameCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_v1_onboarding_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    age_webhook_v1_webhooks_age__provider_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
