/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/age-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Age Status */
        get: operations["age_status_v1_age_verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/age-verification/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Age Session */
        post: operations["start_age_session_v1_age_verification_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/age-verification/sessions/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Age Session */
        get: operations["get_age_session_v1_age_verification_sessions__verification_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/nickname-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nickname Check */
        post: operations["nickname_check_v1_auth_nickname_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_v1_me_patch"];
        trace?: never;
    };
    "/v1/me/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blocks */
        get: operations["blocks_v1_me_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/capsules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Capsules */
        get: operations["list_capsules_v1_me_capsules_get"];
        put?: never;
        /** Create Capsule */
        post: operations["create_capsule_v1_me_capsules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/capsules/{capsule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Capsule */
        delete: operations["delete_capsule_v1_me_capsules__capsule_id__delete"];
        options?: never;
        head?: never;
        /** Rename Capsule */
        patch: operations["rename_capsule_v1_me_capsules__capsule_id__patch"];
        trace?: never;
    };
    "/v1/me/follow-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Follow Requests */
        get: operations["follow_requests_v1_me_follow_requests_get"];
        put?: never;
        /** Decide Request */
        post: operations["decide_request_v1_me_follow_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Followers */
        get: operations["followers_v1_me_followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/followers/{nickname}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Follower
         * @description Togli un follower (o rifiuta la sua richiesta): non vede più il tuo portfolio.
         */
        delete: operations["remove_follower_v1_me_followers__nickname__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Following */
        get: operations["following_v1_me_following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/portfolio/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: operations["reorder_v1_me_portfolio_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Styles */
        get: operations["my_styles_v1_me_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload */
        post: operations["create_upload_v1_media_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["get_upload_v1_media_uploads__upload_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Upload
         * @description Toglie una foto non ancora pubblicata (es. tolta dal carosello prima di postare).
         */
        delete: operations["delete_upload_v1_media_uploads__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload */
        post: operations["complete_upload_v1_media_uploads__upload_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/onboarding/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile_v1_onboarding_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Post */
        post: operations["create_post_v1_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_v1_posts__post_id__get"];
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_v1_posts__post_id__delete"];
        options?: never;
        head?: never;
        /** Update Post */
        patch: operations["update_post_v1_posts__post_id__patch"];
        trace?: never;
    };
    "/v1/posts/{post_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Vote */
        put: operations["vote_v1_posts__post_id__vote_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Styles */
        get: operations["list_styles_v1_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/styles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Style */
        get: operations["get_style_v1_styles__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/styles/{slug}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Join Style */
        put: operations["join_style_v1_styles__slug__membership_put"];
        post?: never;
        /** Leave Style */
        delete: operations["leave_style_v1_styles__slug__membership_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{nickname}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_v1_users__nickname__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{nickname}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Block */
        put: operations["block_v1_users__nickname__block_put"];
        post?: never;
        /**
         * Unblock
         * @description Sblocca. I follow tolti dal blocco non tornano: vanno richiesti di nuovo.
         */
        delete: operations["unblock_v1_users__nickname__block_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{nickname}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow */
        post: operations["follow_v1_users__nickname__follow_post"];
        /**
         * Unfollow
         * @description Smetti di seguire, oppure ritira la richiesta. Ripetibile.
         */
        delete: operations["unfollow_v1_users__nickname__follow_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{nickname}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Posts */
        get: operations["get_user_posts_v1_users__nickname__posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/age/{provider_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Age Webhook */
        post: operations["age_webhook_v1_webhooks_age__provider_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgeSessionIn */
        AgeSessionIn: {
            /**
             * Declared Birth Date
             * Format: date
             */
            declared_birth_date: string;
            /**
             * Method
             * @enum {string}
             */
            method: "selfie_estimation" | "id_document" | "spid" | "cie";
            /** Return Url */
            return_url: string;
        };
        /** AgeSessionOut */
        AgeSessionOut: {
            /** Age Band */
            age_band?: ("16_17" | "18_plus") | null;
            /** Failure Reason */
            failure_reason?: ("underage" | "inconsistent" | "not_completed") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "selfie_estimation" | "id_document" | "spid" | "cie";
            /** Redirect Url */
            redirect_url?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "passed" | "failed" | "expired";
        };
        /** AgeStatusOut */
        AgeStatusOut: {
            /** Age Band */
            age_band?: ("16_17" | "18_plus") | null;
            latest?: components["schemas"]["AgeSessionOut"] | null;
            /** Methods */
            methods: ("selfie_estimation" | "id_document" | "spid" | "cie")[];
            /** Verified */
            verified: boolean;
        };
        /** AuthorRef */
        AuthorRef: {
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "private" | "business";
            /** Nickname */
            nickname: string;
        };
        /** CapsuleIn */
        CapsuleIn: {
            /** Name */
            name: string;
        };
        /** CapsuleOut */
        CapsuleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Post Count */
            post_count: number;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Feature Flags */
            feature_flags: {
                [key: string]: boolean;
            };
            legal: components["schemas"]["LegalLinks"];
            /** Min App Version */
            min_app_version: string;
            /** Styles */
            styles: components["schemas"]["StyleOut"][];
            /** Terms Version */
            terms_version: string;
        };
        /** FeedOut */
        FeedOut: {
            /** Empty Reason */
            empty_reason?: ("no_styles" | "no_posts") | null;
            /** Items */
            items: components["schemas"]["PostOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FollowOut */
        FollowOut: {
            /**
             * Following
             * @enum {string}
             */
            following: "none" | "pending" | "accepted";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemIn */
        ItemIn: {
            /** Brand */
            brand: string;
            /**
             * Currency
             * @default EUR
             * @enum {string}
             */
            currency: "EUR" | "USD" | "GBP" | "CHF";
            /** Media Position */
            media_position?: number | null;
            /** Name */
            name: string;
            /** Pin X */
            pin_x?: number | null;
            /** Pin Y */
            pin_y?: number | null;
            /** Price Cents */
            price_cents?: number | null;
            /** Url */
            url?: string | null;
        };
        /** ItemOut */
        ItemOut: {
            /** Brand */
            brand: string;
            /** Currency */
            currency: string;
            link: components["schemas"]["LinkOut"] | null;
            /** Media Position */
            media_position: number | null;
            /** Name */
            name: string;
            /** Pin X */
            pin_x: number | null;
            /** Pin Y */
            pin_y: number | null;
            /** Position */
            position: number;
            /** Price Cents */
            price_cents: number | null;
        };
        /** LegalLinks */
        LegalLinks: {
            /** Community Rules */
            community_rules: string;
            /** Feed Explainer */
            feed_explainer: string;
            /** Privacy */
            privacy: string;
            /** Terms */
            terms: string;
        };
        /** LinkOut */
        LinkOut: {
            /** Domain */
            domain: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "safe" | "blocked";
            /** Url */
            url: string | null;
        };
        /** MediaOut */
        MediaOut: {
            /** Blurhash */
            blurhash: string;
            /** Height */
            height: number;
            /** Position */
            position: number;
            urls: components["schemas"]["MediaUrls"];
            /** Width */
            width: number;
        };
        /** MediaUrls */
        MediaUrls: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Variants */
            variants: {
                [key: string]: string;
            };
        };
        /** NicknameCheckIn */
        NicknameCheckIn: {
            /** Nickname */
            nickname: string;
        };
        /** NicknameCheckOut */
        NicknameCheckOut: {
            /** Available */
            available: boolean;
            /** Nickname */
            nickname: string;
            /** Reason */
            reason?: ("invalid" | "reserved" | "taken") | null;
        };
        /** OnboardingIn */
        OnboardingIn: {
            /**
             * Accept Community Rules
             * @constant
             */
            accept_community_rules: true;
            /**
             * Account Type
             * @default private
             * @enum {string}
             */
            account_type: "private" | "business";
            /** Nickname */
            nickname: string;
            /** Styles */
            styles: string[];
            /** Terms Version */
            terms_version: string;
        };
        /** OrderIn */
        OrderIn: {
            /** After Id */
            after_id: string | null;
            /**
             * Post Id
             * Format: uuid
             */
            post_id: string;
        };
        /** PeoplePage */
        PeoplePage: {
            /** Items */
            items: components["schemas"]["PersonOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** PersonOut */
        PersonOut: {
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "private" | "business";
            /** Nickname */
            nickname: string;
            /**
             * Since
             * Format: date-time
             */
            since: string;
        };
        /** PortfolioPage */
        PortfolioPage: {
            /** Cover Id */
            cover_id: string | null;
            /** Items */
            items: components["schemas"]["PortfolioTile"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** PortfolioTile */
        PortfolioTile: {
            /** Average */
            average: number | null;
            /** Capsule Id */
            capsule_id: string | null;
            /** Caption */
            caption: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Media Count */
            media_count: number;
            /** Mine */
            mine: number | null;
            photo: components["schemas"]["MediaOut"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "active" | "style_rejected" | "hidden_moderation" | "deleted";
            style: components["schemas"]["StyleRef"];
            /** Vote Count */
            vote_count: number | null;
        };
        /** PostIn */
        PostIn: {
            /** Caption */
            caption?: string | null;
            /** Items */
            items?: components["schemas"]["ItemIn"][];
            /** Media */
            media: string[];
            /** Style */
            style: string;
        };
        /** PostOut */
        PostOut: {
            author: components["schemas"]["AuthorRef"] | null;
            /** Capsule Id */
            capsule_id?: string | null;
            /** Caption */
            caption: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Own */
            is_own: boolean;
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Media */
            media: components["schemas"]["MediaOut"][];
            /** Published At */
            published_at: string | null;
            /** Restyle Available */
            restyle_available?: boolean | null;
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "active" | "style_rejected" | "hidden_moderation" | "deleted";
            style: components["schemas"]["StyleRef"];
            vote: components["schemas"]["VoteSummary"];
        };
        /** PostPatch */
        PostPatch: {
            /** Capsule Id */
            capsule_id?: string | null;
            /** Caption */
            caption?: string | null;
            /** Items */
            items?: components["schemas"]["ItemIn"][] | null;
            /** Style */
            style?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "private" | "business";
            /**
             * Age Band
             * @enum {string}
             */
            age_band: "16_17" | "18_plus";
            /** Bio */
            bio: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Hide Prices */
            hide_prices: boolean;
            /** Hide Vote Count */
            hide_vote_count: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "suspended" | "pending_deletion";
            /** Styles */
            styles: string[];
        };
        /** ProfileUpdateIn */
        ProfileUpdateIn: {
            /** Account Type */
            account_type?: ("private" | "business") | null;
            /** Bio */
            bio?: string | null;
            /** Hide Prices */
            hide_prices?: boolean | null;
            /** Hide Vote Count */
            hide_vote_count?: boolean | null;
        };
        /** Relationship */
        Relationship: {
            /**
             * Following
             * @enum {string}
             */
            following: "none" | "pending" | "accepted";
            /** Follows You */
            follows_you: boolean;
        };
        /** RequestDecision */
        RequestDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject";
            /** Nickname */
            nickname: string;
        };
        /** StyleCard */
        StyleCard: {
            /** Active Until */
            active_until: string | null;
            /** Joined */
            joined: boolean;
            /** Member Count */
            member_count: number;
            /**
             * Min Age Band
             * @enum {string}
             */
            min_age_band: "16_17" | "18_plus";
            /** Name */
            name: string;
            /** Seasonal */
            seasonal: boolean;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
            /** Tone */
            tone: string;
        };
        /** StyleDetail */
        StyleDetail: {
            /** Active Until */
            active_until: string | null;
            /** Joined */
            joined: boolean;
            /** Member Count */
            member_count: number;
            /**
             * Min Age Band
             * @enum {string}
             */
            min_age_band: "16_17" | "18_plus";
            /** Name */
            name: string;
            /** Posts Last 7 Days */
            posts_last_7_days: number;
            /** Seasonal */
            seasonal: boolean;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
            /** Tone */
            tone: string;
        };
        /** StyleList */
        StyleList: {
            /** Items */
            items: components["schemas"]["StyleCard"][];
            /** Total */
            total: number;
        };
        /** StyleOut */
        StyleOut: {
            /** Active Until */
            active_until: string | null;
            /** Min Age Band */
            min_age_band: string;
            /** Name */
            name: string;
            /** Seasonal */
            seasonal: boolean;
            /** Slug */
            slug: string;
            /** Tagline */
            tagline: string;
            /** Tone */
            tone: string;
        };
        /** StyleRef */
        StyleRef: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Tone */
            tone: string;
        };
        /** UploadIn */
        UploadIn: {
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp";
            /** Size Bytes */
            size_bytes: number;
        };
        /** UploadOut */
        UploadOut: {
            /** Blurhash */
            blurhash?: string | null;
            /** Height */
            height?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Bytes */
            max_bytes?: number | null;
            /** Reject Reason */
            reject_reason?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "rejected";
            upload?: components["schemas"]["UploadTarget"] | null;
            /** Upload Expires At */
            upload_expires_at?: string | null;
            urls?: components["schemas"]["MediaUrls"] | null;
            /** Width */
            width?: number | null;
        };
        /**
         * UploadTarget
         * @description POST multipart: tutti i `fields` e per ultimo il file nel campo `file`.
         */
        UploadTarget: {
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Url */
            url: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Account Type
             * @enum {string}
             */
            account_type: "private" | "business";
            /** Bio */
            bio: string | null;
            /** Can View Posts */
            can_view_posts: boolean;
            /** Capsules */
            capsules: components["schemas"]["CapsuleOut"][];
            /** Followers */
            followers: number;
            /** Following */
            following: number;
            /** Is Self */
            is_self: boolean;
            /** Nickname */
            nickname: string;
            /** Pending Requests */
            pending_requests?: number | null;
            relationship: components["schemas"]["Relationship"];
            stats: components["schemas"]["UserStats"];
            /** Styles */
            styles: components["schemas"]["StyleRef"][];
        };
        /** UserStats */
        UserStats: {
            /** Average */
            average: number | null;
            /** Posts */
            posts: number;
            /** Votes */
            votes: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoteIn */
        VoteIn: {
            /** Score */
            score: number;
            /** Style Confirm */
            style_confirm?: boolean | null;
        };
        /** VoteSummary */
        VoteSummary: {
            /** Ask Style Confirm */
            ask_style_confirm: boolean;
            /** Average */
            average: number | null;
            /** Mine */
            mine: number | null;
            /** My Style Confirm */
            my_style_confirm: boolean | null;
            /** Style Match */
            style_match: number | null;
            /** Vote Count */
            vote_count: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    age_status_v1_age_verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeStatusOut"];
                };
            };
        };
    };
    start_age_session_v1_age_verification_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgeSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_age_session_v1_age_verification_sessions__verification_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nickname_check_v1_auth_nickname_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NicknameCheckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NicknameCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    get_feed_v1_feed_get: {
        parameters: {
            query?: {
                style?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_me_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blocks_v1_me_blocks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_capsules_v1_me_capsules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapsuleOut"][];
                };
            };
        };
    };
    create_capsule_v1_me_capsules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapsuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapsuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_capsule_v1_me_capsules__capsule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capsule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_capsule_v1_me_capsules__capsule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capsule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapsuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapsuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_requests_v1_me_follow_requests_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_request_v1_me_follow_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    followers_v1_me_followers_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_follower_v1_me_followers__nickname__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    following_v1_me_following_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeoplePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_v1_me_portfolio_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_styles_v1_me_styles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleList"];
                };
            };
        };
    };
    create_upload_v1_media_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_v1_media_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upload_v1_media_uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_v1_media_uploads__upload_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_v1_onboarding_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_v1_posts_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_v1_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_v1_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_v1_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vote_v1_posts__post_id__vote_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_styles_v1_styles_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_style_v1_styles__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_style_v1_styles__slug__membership_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_style_v1_styles__slug__membership_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_v1_users__nickname__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_v1_users__nickname__block_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_v1_users__nickname__block_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_v1_users__nickname__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_v1_users__nickname__follow_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_posts_v1_users__nickname__posts_get: {
        parameters: {
            query?: {
                capsule?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    age_webhook_v1_webhooks_age__provider_name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
